services:
    sonata.admin.article.article:
        class: ProjetNormandie\ArticleBundle\Admin\ArticleAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "group.articles", label: "label.article" }
        arguments:
            - ~
            - ProjetNormandie\ArticleBundle\Entity\Article
            - ~
    sonata.admin.article.comment:
        class: ProjetNormandie\ArticleBundle\Admin\CommentAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "group.articles", label: "label.comment" }
        arguments:
            - ~
            - ProjetNormandie\ArticleBundle\Entity\Comment
            - ~
