services:
    sonata.admin.article.article:
        class: ProjetNormandie\ArticleBundle\Admin\ArticleAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Articles", label: "Article" }
        arguments:
            - ~
            - ProjetNormandie\ArticleBundle\Entity\Article
            - ~
