resources:
    ProjetNormandie\ArticleBundle\Entity\Article:
      collectionOperations:
          get:
              normalization_context: {'groups': [article.list]}
      itemOperations:
          get:
              normalization_context: {'groups': [article.show, user.autocomplete]}
