ProjetNormandie\ArticleBundle\Entity\Article:
  attributes:
    id:
      groups:
        - 'article.list'
        - 'article.show'
    author:
      groups:
        - 'article.show'
    title:
      groups:
        - 'article.list'
        - 'article.show'
    text:
      groups:
        - 'article.show'
    status:
      groups:
        - 'article.list'
        - 'article.show'
    createdAt:
      groups: []
    updatedAt:
      groups: []
    publishedAt:
      groups:
        - 'article.list'
        - 'article.show'
