ProjetNormandie\ArticleBundle\Entity\Comment:
  attributes:
    id:
      groups:
        - 'article.comment.read'
    article:
      groups:
        - 'article.comment.post'
    user:
      groups:
        - 'article.comment.user'
    text:
      groups:
        - 'article.comment.read'
        - 'article.comment.post'
    createdAt:
      groups:
        - 'article.comment.read'
    updatedAt:
      groups: []
