services:
    sonata.admin.article.article:
        class: ProjetNormandie\ArticleBundle\Admin\ArticleAdmin
        tags:
            -
                name: sonata.admin
                model_class: ProjetNormandie\ArticleBundle\Entity\Article
                manager_type: orm
                group: "group.articles"
                label: "label.article"
        calls:
            - [ setSecurity, [ '@security.helper' ] ]
    sonata.admin.article.comment:
        class: ProjetNormandie\ArticleBundle\Admin\CommentAdmin
        tags:
            -
                name: sonata.admin
                model_class: ProjetNormandie\ArticleBundle\Entity\Comment
                manager_type: orm
                group: "group.articles"
                label: "label.comment"
