services:
  _defaults:
    autowire: true
    autoconfigure: true

  ProjetNormandie\ArticleBundle\:
    resource: '../src/*'
    exclude: '../src/{Admin,Entity,DependencyInjection,Migrations,Tests,Kernel.php}'

  pn.article.event.entity.article:
    class: ProjetNormandie\ArticleBundle\EventListener\Entity\ArticleListener
    tags:
      - { name: doctrine.orm.entity_listener }

  pn.article.event.entity.comment:
    class: ProjetNormandie\ArticleBundle\EventListener\Entity\CommentListener
    tags:
      - { name: doctrine.orm.entity_listener }
