services:
  _defaults:
    autowire: true
    autoconfigure: true

  ProjetNormandie\ArticleBundle\:
    resource: '../src/*'
    exclude: '../src/{Admin,Entity,DependencyInjection,Migrations,Tests,Kernel.php}'

  ProjetNormandie\ArticleBundle\Doctrine\TranslationExtension:
    arguments:
      - '@request_stack'
    tags:
      - { name: api_platform.doctrine.orm.query_extension.collection }
      - { name: api_platform.doctrine.orm.query_extension.item }

  pn.article.event.entity.article:
    class: ProjetNormandie\ArticleBundle\EventListener\Entity\ArticleListener
    arguments:
      - '@security.helper'
      - '@slugger'
    tags:
      - { name: doctrine.orm.entity_listener }

  pn.article.event.entity.article_translation:
    class: ProjetNormandie\ArticleBundle\EventListener\Entity\ArticleTranslationListener
    arguments:
      - '@slugger'
    tags:
      - { name: doctrine.orm.entity_listener }

  pn.article.event.entity.comment:
    class: ProjetNormandie\ArticleBundle\EventListener\Entity\CommentListener
    tags:
      - { name: doctrine.orm.entity_listener }

  pn.article.builder.article:
    class: ProjetNormandie\ArticleBundle\Builder\ArticleBuilder
    arguments:
      - '@doctrine.orm.default_entity_manager'