ProjetNormandie\ArticleBundle\Entity\Article:
  attributes:
    slug:
      groups:
        - 'article:read'
    createdAt:
      groups:
        - 'article:read'
    updatedAt:
      groups:
        - 'article:read'
