ProjetNormandie\UserBundle\Entity\User:
  attributes:
    id:
      groups:
        - 'article.user.read'
    username:
      groups:
        - 'article.user.read'
    avatar:
      groups:
        - 'article.user.read'
    slug:
      groups:
        - 'article.user.read'
    isOnline:
      groups:
        - 'article.user.read'

